### ISSUE TITLE
Feature 3 공동개발내역 확인.

### ISSUE THREAD

**Issue by Minseojeonn** [raichal2000/OSS-JBNU-2022#28]
**Is your feature request related to a problem? Please describe.**
피처3에 대해서.
민서  - 크롤링 하는 부분 코드 짜서 올리기 
지호  -  크롤링 해온 부분 데이터 처리해서, dict에 담기 및 별 알고리즘 구현
현석  -  bot을 이용해서 출력하는 부분 작성 ( dict에서 맞는 부분 따오기)

**Describe alternatives you've considered**

딱히 없습니다.

**Additional context**

Feature3 - 기간 준수 부탁드립니다. ( 이번주 금요일)

**Comment by hyun4325** [comment]
어 저 이름이 잘못되어있어요

**Comment by Minseojeonn** [comment]
> 어 저 이름이 잘못되어있어요

바꿧어요 ㅎㅎㅎㅎ 죄송합니다
